version: "3.8"

services:
  db:
    image: postgres:13-alpine
    container_name: dev-db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - devnet

  adminer:
    image: adminer:latest
    container_name: dev-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - devnet

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev-app
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      - devnet

  nginx:
    image: nginx:latest
    container_name: dev-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - adminer
    networks:
      - devnet

volumes:
  db-data:

networks:
  devnet:
