version: "3.8"

services:
  db:
    image: postgres:13-alpine
    container_name: dev-db
    restart: unless-stopped
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: docker.dev-db
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - devnet
    depends_on:
      - fluentd

  adminer:
    image: adminer:latest
    container_name: dev-adminer
    restart: unless-stopped
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: docker.dev-adminer
    ports:
      - "8080:8080"
    networks:
      - devnet
    depends_on:
      - fluentd

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev-app
    restart: unless-stopped
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: docker.dev-app
    env_file:
      - .env
    depends_on:
      - db
      - fluentd
    ports:
      - "5000:5000"
    networks:
      - devnet

  nginx:
    image: nginx:latest
    container_name: dev-nginx
    restart: unless-stopped
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: docker.dev-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - adminer
      - fluentd
    networks:
      - devnet

  fluentd:
    image: fluent/fluentd:v1.16-1
    container_name: dev-fluentd
    restart: unless-stopped
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf:ro
    networks:
      - devnet

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: dev-elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - devnet

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: dev-kibana
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - devnet

volumes:
  db-data:
  esdata:

networks:
  devnet:
